name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Debug Environment
      run: |
        echo "Checking if MONGODB_URI is set (will not print value)"
        if [ -n "$MONGODB_URI" ]; then echo "MONGODB_URI is set"; else echo "MONGODB_URI is not set"; fi
    
    - name: Run tests
      run: |
        pytest -v
      env:
        MONGODB_URI: ${{ secrets.ANKIT_MONGO_URI }}
        PYTHONPATH: ${{ github.workspace }}
